mywordsbank/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('wordsbank.urls')),
    url(r'^admin/', admin.site.urls),
]

wordsbank/urls.py
from django.conf.urls import url

from . import views

app_name = 'wordsbank'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'words_bank$', views.WordsBankView.as_view(), name='WordsBank'),
    url(r'words_bank/search$', views.search, name='search'),
    url(r'words_bank/(?P<word_text>\w+)/$', views.detail, name='detail'),
    url(r'save_word$', views.save_word, name='save_word'),
    url(r'upload$', views.upload, name='upload'),
    url(r'upload_file$', views.upload_file, name='upload_file'),
    url(r'download_file$', views.download_file, name='download_file'),
    url(r'delete_all$', views.delete_all, name='delete_all'),

]
# url(r'^(?P<question_id>[a-z]+)/$', views.DetailView.as_view(), name='detail'),
# Regular Expression
# [0-9] (+) so on...
# ?P(parameter)<...>

wordsbank/models.py
from django.db import models

# Create your models here.


class Word(models.Model):
    word_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.word_text


class Detail(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    type = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    example = models.CharField(max_length=200)

    def __str__(self):
        return self.type + self.description + self.example

wordsbank/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect , HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Word, Detail
from django.utils import timezone
import csv, os
from django.core.files.storage import default_storage


class HomeView(generic.ListView):
    template_name = 'wordsbank/home.html'

    def get_queryset(self):

        return None


def search(request):
    word = request.POST['search']
    return HttpResponseRedirect(reverse('wordsbank:detail', args={word}))


def detail(request, word_text):

    try:
        Word.objects.get(word_text=word_text)
    except Word.DoesNotExist:
        return render(request, 'wordsbank/detail.html', {
            'error_message': "Word not found!.",
        })
    else:
        word_show = Word.objects.get(word_text=word_text)
        return render(request, 'wordsbank/detail.html', {'word': word_show})


def save_word(request):

    word_save = str(request.POST['word'])
    type_save = str(request.POST['type'])
    description_save = str(request.POST['description'])
    example_save = str(request.POST['example'])

    if word_save == "" or description_save == "" or example_save == "":
        return render(request, 'wordsbank/home.html', {
            'error_message': "Please fill in the form completely.",
        })
    else:
        if not Word.objects.filter(word_text=word_save):  # Don't have word
            new_word = Word(word_text=word_save, pub_date=timezone.now())
            new_word.save()
            new_word.detail_set.create(type=type_save, description=description_save, example=example_save)
        else:
            word_current = Word.objects.get(word_text=word_save)
            word_current.detail_set.create(type=type_save, description=description_save, example=example_save)

    return HttpResponseRedirect(reverse('wordsbank:WordsBank'))


def upload(request):
    return render(request,'wordsbank/upload.html')


def upload_file(request):
    dir_path = 'wordsbank/static/wordsbank/'
    csv_file = request.FILES['csvfile']
    file_path = default_storage.save(dir_path, csv_file)
    os.rename(file_path, "{}word_bank.csv".format(dir_path))
    with open("{}word_bank.csv".format(dir_path), encoding='utf-8') as csvfile:
        dataReader = csv.DictReader(csvfile)

        for row in dataReader:
            if row["Word"] != "":
                word = row["Word"]
                if Word.objects.filter(word_text=word):  # if have word
                    word_add = Word.objects.get(word_text=word)  # get word
                else:  # if not have word
                    word_add = Word(word_text=word, pub_date=timezone.now())  # create new word
                word_add.save()

            if row["Type"] != "":
                type = row["Type"]
                word_add.save()

            if row["Description"] != "":
                description = row["Description"]
                word_add.save()

            if row["Example"] != "":
                example = row["Example"]
                word_add.detail_set.create(type=type, description=description, example=example)
                word_add.save()

    return HttpResponseRedirect(reverse('wordsbank:WordsBank'))


def download_file(request):
    with open('wordsbank/static/wordsbank/word_bank.csv', 'w')as csvfile:
                fieldnames = ['Word', 'Type', 'Description', 'Example']
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
                writer.writeheader()
                word_all = Word.objects.order_by('word_text')

                for word in word_all:
                    current_word = Word.objects.get(word_text=word)
                    current_detail = current_word.detail_set.all()
                    if len(current_detail) > 1:
                        j = 1  # use for count if len(crrent_detail) > 1 for create table that in row 'Word' must empty
                        for info in current_detail:
                            if j > 1:  # new line that 'Word' must empty
                                writer.writerow(
                                    dict(Word='', Type=info.type, Description=info.description, Example=info.example))
                            else:
                                writer.writerow(
                                    dict(Word=word, Type=info.type, Description=info.description, Example=info.example))
                            j += 1

                    else:
                        for info in current_detail:
                            writer.writerow(
                                dict(Word=word, Type=info.type, Description=info.description, Example=info.example))

    return HttpResponseRedirect(reverse('wordsbank:upload'))


def delete_all(request):
    word_all = Word.objects.all()
    word_all.delete()
    return render(request,'wordsbank/words_bank.html')



class WordsBankView(generic.ListView):
    template_name = 'wordsbank/words_bank.html'
    context_object_name = 'latest_word_list'

    def get_queryset(self):

        return Word.objects.order_by('word_text')

wordsbank/templates/wordsbank/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ word.word_text }}</title>
    {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'wordsbank/style.css' %}" />
</head>
<body>
<ul>
  <li><a href="{% url 'wordsbank:home' %}">Home</a></li>
  <li><a href="{% url 'wordsbank:WordsBank' %}">Words Bank</a></li>
     <li><a href="{% url 'wordsbank:upload' %}">Download / Upload</a></li>
  <ul style="float:right;list-style-type:none;">
    <li><a href="#about">About</a></li>
    <li><a href="admin">Admin</a></li>
  </ul>
</ul>

{% if error_message %}<p style="text-align: center; font-size:150%;"><strong>{{ error_message }}</strong></p>
{% else %}
<h1 style="text-indent: 1%">  {{ word.word_text }}</h1>

{% for detail in word.detail_set.all %}
<pre style="font-size:18px; text-indent: 1%;" ><b>Type:</b> {{ detail.type}} </pre>
<pre style="font-size:18px; text-indent: 1%;" ><b>Description:</b> {{ detail.description}} </pre>
<pre style="font-size:18px; text-indent: 1%;" ><b>Example:</b> {{ detail.example }}</pre>
{% endfor %}
{% endif %}
</body>
</html>

wordsbank/templates/wordsbank/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>


<style>
body {margin:0;}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
    border-right:1px solid #bbb;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}


div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 40px;

    width:50%;
    margin: auto;
    padding: 10px;

}

input[type=text], select {

}

input[type=submit] {
    width: 25%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
}

.middle-save-bt{
    margin: 8px 37% -8px;
    }

.word-text{
    width: 100%;
    height: 25%;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
    }

.search {
        width: 30%;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image:  url('images/search.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    }

input[type=submit]:hover {
    background-color: #45a049;
}

div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 40px;
}

textarea {
    width: 100%;
    height: 25%;
    padding: 12px 20px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    background-color: #f8f8f8;
    font-size: 16px;
    resize: none;
}


select {
    width: 100%;
    padding: 16px 20px;
    border: none;
    border-radius: 4px;
    background-color: ;
}

</style>

</head>
<body>

<ul>
  <li><a class="active" href="{% url 'wordsbank:home' %}">Home</a></li>
  <li><a href="{% url 'wordsbank:WordsBank' %}">Words Bank</a></li>
    <li><a href="{% url 'wordsbank:upload' %}">Download / Upload</a></li>
  <ul style="float:right;list-style-type:none;">
    <li><a href="#about">About</a></li>
    <li><a href="admin">Admin</a></li>
  </ul>
</ul>
<br>
<br>
<br>
<br>
<br>
<br>

<div>
  <form action="{% url 'wordsbank:save_word' %}" method="post">
      {% csrf_token %}
      <pre style="text-align:center;font-size:30px;">Save Your Word</pre>
    <label for="word" ><b>Word</b></label><br><br>
    <input placeholder="Word" class="word-text" type="text" id="word" name="word">

    <br><br>
  <label for="type"><b>Type</b></label><br><br>
  <select id="type" name="type">
    <option value="Noun">Noun</option>
    <option value="Pronoun">Pronoun</option>
    <option value="Verb">Verb</option>
    <option value="Adjective">Adjective</option>
    <option value="Adverb">Adverb</option>
    <option value="Conjunction">Conjunction</option>
    <option value="Interjection">Interjection</option>
</select><br><br>

    <label for="description"><b>Description</b></label>
<br><br>
    <textarea placeholder="Type of word , meaning , etc." id="description" name="description"></textarea>


    <br><br>
    <label for="example"><b>Example</b></label>
    <br><br>
    <textarea placeholder="Write some example" id="example" name="example"></textarea>



    <input type="submit" class="middle-save-bt" value="Save">
  </form>
</div>

{% if error_message %}<p style="text-align: center; font-size:150%;"><strong>{{ error_message }}</strong></p>{% endif %}


</body>
</html>

wordsbank/templates/wordsbank/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload - Download</title>
    {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordsbank/style.css' %}" />
</head>
<body>

<ul>
  <li><a href="{% url 'wordsbank:home' %}">Home</a></li>
  <li><a href="{% url 'wordsbank:WordsBank' %}">Words Bank</a></li>
     <li><a class="active" href="{% url 'wordsbank:upload' %}">Download / Upload</a></li>
  <ul style="float:right;list-style-type:none;">
    <li><a href="#about">About</a></li>
    <li><a href="admin">Admin</a></li>
  </ul>
</ul>


<h1>Upload word from CSV file</h1>
<form action="{% url 'wordsbank:upload_file' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
Open File:
<input type="file" name="csvfile" id="csvfile"><br><br>
<input type="submit" value="Upload CSV File" name="submit">

</form>

<br><br><br>
<p><b>Click on the download to download the csv file:<b/><p>

<a href="{% static 'wordsbank/word_bank.csv' %}" download>
  <img border="0" src="{% static 'wordsbank/images/Download-Button.png' %}" alt="wordsbank" width="20%" height="5%">
</a>

</body>


</html>

wordsbank/templates/wordsbank/words_bank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Words Bank</title>
</head>

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'wordsbank/style.css' %}" />

<style>
    table {
    font-size:19px;

    border-collapse: collapse;
    margin:auto;
    width: 99%;
}

 td,th {
    border: 1px solid #ddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}
th {
    padding-top: 11px;
    padding-bottom: 11px;
    background-color: #4CAF50;
    color: white;
}
</style>

</head>
<body>

<ul>
  <li><a href="{% url 'wordsbank:home' %}">Home</a></li>
  <li><a class="active" href="{% url 'wordsbank:WordsBank' %}">Words Bank</a></li>
     <li><a href="{% url 'wordsbank:upload' %}">Download / Upload</a></li>
  <ul style="float:right;list-style-type:none;">
    <li><a href="#about">About</a></li>
    <li><a href="admin">Admin</a></li>
  </ul>
</ul>

<form action="{% url 'wordsbank:search' %}" method="POST">
    {% csrf_token %}
    <input placeholder="Search" class="search" type="text" id="search" name="search">

</form>

    <h1 style="text-align:center;" > Your Words Bank</h1>
    {% if latest_word_list %}




        <table id="t01">



        <tr>
            <th>Word</th>
            <th>Type</th>
            <th>Description</th>
            <th>Example</th>
         </tr>
         {% for word in latest_word_list %}
         {% for detail in word.detail_set.all %}
            {% if word.detail_set.all %}
        <tr>    {% if forloop.first %}
                <td>{{word.word_text}}</td>
                {% else %}
                <td> </td>
                {% endif %}
                <td>{{ detail.type}} </td>
                <td>{{ detail.description}} </td>
                <td> {{ detail.example}} </td>
            {% else %}
                No details.
            {% endif %}

        </tr>
        {% endfor %}
        {% endfor %}

            </table><br>



<center>Click save then you can download file form Download/Upload menu. </center>
<form action="{% url 'wordsbank:download_file' %}" method="post">
    {% csrf_token %}
<input type="submit" class="middle-save-bt" value="Save">
<br><br>
</form>

<center> Delete all words click here </center>
<form action="{% url 'wordsbank:delete_all' %}" method="post">
    {% csrf_token %}
<input type="submit" class="middle-save-bt" value="Delete">

</form>



    {% else %}
       <center> <p>No Words are available.</p></center>
    {% endif %}




</body>
</html>